# Generated by Django 4.1.1 on 2022-09-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_personal_info_is_seller_personal_info_seller_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='profile_Picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
